#5-Added carousel and Latest Events Section
himanshu-dhiman/WP_RSVP pull request #16
Opened 2017-07-18 07:34 UTC by himanshu-dhiman

2017-07-18 11:01 UTC, Shubham2301 requested changes

2017-07-18 11:01 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +			<div id="carouselExampleIndicators" class="carousel slide"  data-ride="carousel">
naming convention

2017-07-18 11:01 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +							<h3>#SOIREE 1.</h3>
use css for font-size

2017-07-18 11:01 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/src/scss/style.scss
> +	@extend .marcellus-sc;
name font classes as: .font-font-name

2017-07-19 05:10 UTC, rathorevaibhav requested changes
Just some feedback. Everything else looks good.

2017-07-19 05:10 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +					  	<img class="d-block img-fluid images_carousel" src="<?php echo esc_url(get_template_directory_uri()."/rsvp_images/soiree4.jpg");?>" alt="third slide">
always prefer single quotes in PHP. Single and double quotes work differently in PHP.

2017-07-19 05:10 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +					  	<img class="d-block img-fluid images_carousel" src="<?php echo esc_url(get_template_directory_uri()."/rsvp_images/soiree2.jpg");?>" alt="Second slide">
prefer single quotes in PHP.

2017-07-19 05:10 UTC, rathorevaibhav commented on public/wp-content/themes/ColoredCow/landing.php
> +					<li data-target="#carousel-example-indicators" data-slide-to="0" class="active"></li>
carousel-example???? Can you name your carousel better?

2017-07-19 05:10 UTC, Shubham2301 requested changes

2017-07-19 05:10 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +						<p class="carousel-head">#SOIREE 1</p>
indent

2017-07-19 05:10 UTC, Shubham2301 commented on public/wp-content/themes/ColoredCow/landing.php
> +						<p class="carousel-head">#SOIREE 2</p>
indent

2017-07-19 05:26 UTC, merged